DELETE http://localhost:9000/plovilo/1
Accept: application/json

###
PUT http://localhost:9000/plovilo/1
Accept: application/json

###
POST http://localhost:9000/plovilo
Accept: application/json

###
GET http://localhost:9000/plovilo/1
Accept: application/json

###
GET http://localhost:9000/plovilo
Accept: application/json


###

###
